### PR TITLE
System.Device

### PR DESCRIPTION
**Pull request by danmosemsft**
Code for System.Device.dll, the wrapper around the Windows COM-based Location API (https://docs.microsoft.com/en-us/windows/win32/api/locationapi/)

### CODE REVIEW

**Comment by danmosemsft** [comment]
@terrajobst 

@rbhanda can you please give myself and @terrajobst write access to this repo? we can bug you less often 😄

**Comment by terrajobst** [comment]
> @terrajobst write access to this repo?

I've got write access :-)

**Comment by dotMorten** [comment]
Nice! Thank you!

**Comment by dotMorten** [comment]
I legally allowed to fork that code and port it to .NET Core and publish a nuget package?

**Comment by danmosemsft** [comment]
@dotMorten I refer you to the license 😄  https://github.com/microsoft/referencesource/blob/master/LICENSE.txt

**Comment by danmosemsft** [comment]
If you do, though @terrajobst  -- any guidance about the namespace and the naming of such a package?

**Comment by dotMorten** [comment]
I'd use the same namespace for app-compat, but recommendations for package ID would be helpful.

**Comment by danmosemsft** [comment]
Note that this repo does not automatically mirror to the [source browser](https://referencesource.microsoft.com/). The process to update that is pretty manual and we don't have a plan to do it right now.

**Comment by dotMorten** [comment]
@danmosemsft Somethings seems off. For instance there are two `GeoCoodinate` classes:
https://github.com/microsoft/referencesource/pull/120/files#diff-acb6b327f93669dd20f93b7165bcfea2R21
https://github.com/microsoft/referencesource/pull/120/files#diff-5f1a5545a79572e4fe3aec1a9b18fc09R21

And two `CivicAddress` classes:
https://github.com/microsoft/referencesource/pull/120/files#diff-748d1c8dc175db526eb8fcfaebd9ca4cR22
https://github.com/microsoft/referencesource/pull/120/files#diff-b44081b982e5f09d8fcb8ea09a371a2fR23

**Comment by dotMorten** [comment]
...excluding these four files makes it build. I don't think those are part of .NET Framework?
 - `CivicAddress.cs`
 - `LocationCoordinate.cs`
 - `LocationProvider.cs`
 - `LocationProviderInternal.cs`

**Comment by dotMorten** [comment]
Ported! https://github.com/dotMorten/System.Device

**Comment by sveroa** [comment]
Worked in my MVC web app...Perfect @dotMorten 👍

**Pull request merged**
